### ISSUE TITLE
Add Windows 10 to build and test process.

### ISSUE THREAD

**Issue by minesh-s-patel** [finos/common-domain-model#2176] opened 2023-06-07 08:27 UTC
@tomhealey-icma has reported that the maven build is failing. 
The build is successfully on Linux and MacOS.

There is already issue #2111 to create a CI build to validate on windows. 
GitHub Actions supports running the maven on windows.

**Comment by chrisisla** [comment] 2023-06-08 15:23
Hi @maoo,
On the TAWG meeting today (#2172 ) this issue was raised. It was suggested that this could be resolved with a new workflow in github actions. Your name was mentioned in conjunction with this. Is there any assistance you could provide @tomhealey-icma on resolving this?
Thanks!

**Comment by maoo** [comment] 2023-06-08 15:36
Hi @chrisisla - happy to support!

@tomhealey-icma - could you please post the steps to reproduce the issue and pointers to any documentation that you followed?

I'd like to first address the issue of building CDM locally on Windows, and then think about CI with GitHub Actions, maybe coordinating this activity with the migration from CodeFresh to GitHub Actions.

WDYT?

**Comment by maoo** [comment] 2023-06-09 10:44
Thanks @tomhealey-icma . Could you also attach logs into gist.github.com and drop the URL here?

I tried on my end and everything worked:
```
vagrant init senglin/win-10-enterprise-vs2015community --box-version 1.0.0
vagrant up
[installed oracle JDK 20.x and Maven 3.x]
git clone https://github.com/finos/common-domain-model.git
cd common-domain-model
mvn install -DskipTests
```
Note that I'm using a `master` branch.

Now testing a `mvn install` to see if tests are failing, but it will take a while.

@minesh-s-patel - anyone on your team running on Windows that can try to reproduce the issue?

**Comment by maoo** [comment] 2023-06-12 11:26
Hi @tomhealey-icma - unfortunately I don't have Windows, so I am running on a VM with 4GB RAM, which is quite limited, and I cannot run the entire build process. This is what I did:

```
git clone https://github.com/finos/common-domain-model
git checkout 4.0.0-dev.49
cd common-domain-model/scheme-import
mvn test -Dtest=SchemeImporterTest --settings ../settings.xml
```

And it run successful; please note that the `--settings ./settings.xml` should not be needed, since dependencies are all publicly resolved (@minesh-s-patel - please correct me if I'm wrong).

Looking at your stacktrace, the issue generates from `com.regnosys.testing.schemaimport.iso.currency.IsoCurrencySchemeEnumReader.parseSchemaFile(IsoCurrencySchemeEnumReader.java:69)` , but I can't find `IsoCurrencySchemeEnumReader.java`; @minesh-s-patel and team maybe can help finding out where this file is.

Last, @tomhealey-icma , I'd suggest adding a `-X` option to your `mvn` commands to get a `DEBUG` output and try to find out which exact schema file is failing ; it seems that Xerces is complaining about an XSD file being invalid, but we need to have more info to fin out what's going on.

If the issue is intermittent, I'd guess that the problem lies in the workstation's configuration, but a) I may be wrong and b) there may be some `try/catch` logic to prevent this to happen in the future and/or guide developers on how to solve the issue.

**Comment by tomhealey-icma** [comment] 2023-06-12 12:31
@maoo - We've already identified the issue is related to pathnames names that cannot be correctly converted to windows pathnames. This request is to add a windows 10 build process in codefresh so every build and release works across all platforms. Can you add this to the process?

**Comment by tomhealey-icma** [comment] 2023-06-12 13:23
Can we add windows 10 to codefresh until we have github actions in place?

**Comment by maoo** [comment] 2023-06-12 13:28
Looks like [CodeFresh provides support for Windows](https://codefresh.io/docs/docs/incubation/windows/). I don't have access to the CodeFresh dashboard, so I'll defer to @minesh-s-patel on this.

**Comment by minesh-s-patel** [comment] 2023-06-21 10:47
@maoo @tomhealey-icma 
We can do this in a Git Hub action rather then Codefresh. Codefresh does not support Windows builds and the builds can co-exist.

**Comment by minesh-s-patel** [comment] 2023-06-21 10:49
> Below the code for the GitHub Action; you can save it as `.github/workflows/windows-build.yaml` and push it in a branch; every new push to the branch will trigger the action; if you want to run it manually, you can add `on: [workflow_dispatch]` right after the `name` field (line 2).

I think this action is very close to what is needed. Thanks @maoo

**Comment by tomhealey-icma** [comment] 2023-07-17 20:06
@maoo - have you been able to add the windows build as suggested by minesh?

**Comment by maoo** [comment] 2023-07-18 12:18
> @maoo - have you been able to add the windows build as suggested by minesh?

Sorry @tomhealey-icma , it's very hard for me to find time to contribute directly to the 50+ projects that we host.

That said, I think that [this comment](https://github.com/finos/common-domain-model/issues/2176#issuecomment-1587309498) provides the code needed, so it would be a fairly straight-forward to give it try.

Hopefully someone from the community will volunteer to tackle this (FYI @eteridvalishvili).

**Comment by eteridvalishvili** [comment] 2023-07-25 04:31
@maoo and @tomhealey-icma I have included this as an item for tomorrows Contribution Review WG https://github.com/finos/common-domain-model/issues/2277

**Comment by minesh-s-patel** [comment] 2023-09-14 14:04
@tomhealey-icma 

To add a github action, we simply need to create a yml file in the `.github/workflows` dir. 
See docs here: https://docs.github.com/en/actions/quickstart

@maoo Already gave the command that we need.

```
name: CDM Build on Windows machine
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven install
        run: mvn install

```

When you make the change in a PR - you will see the new checks made. Can you please give this a go and see if it works? Happy to support you and review/approve the PR.

**Comment by tomhealey-icma** [comment] 2023-09-18 16:47
I created a file windows-build.yml with the above content except change java 11 to 17. Added the file to the PR but the build fails with the message build was terminated by pipeline policy. @maoo - any suggestions.

**Closed** 2023-10-17 02:02 UTC
Labels: help wanted
