### ISSUE TITLE
Emums should be formatted in UpperCamelCase

### ISSUE THREAD

**Issue by hugohills-regnosys** [finos/common-domain-model#2072] opened 2023-03-24 22:42 UTC
Enums should be formatted in UpperCamelCase, with the exception of: 
- enums linked to external schemas such as FpML coding schemes, e.g., `BusinessCenterEnum` which is linked to http://www.fpml.org/coding-scheme/business-center
- other exceptions?

There are a number of enums that do not conform such as `EventTimestampQualificationEnum`.  Needs reviewing and amending.

**Comment by tomhealey-icma** [comment] 2023-03-26 13:33
Now that this is up for discussion. I prefer enumerations in all upper case with the underscore as the only special character. Any other domain definition, FIX, FpML, SFTR should be done through mapping synonyms.

**Comment by tomhealey-icma** [comment] 2023-09-01 11:50
Closed

**Comment by lolabeis** [comment] 2023-09-01 13:27
This issue is referenced in PR #2060 that got merged, but that PR only surfaced the issue, it did not close it. Therefore the issue is still open.

**Closed** 2023-10-17 08:16 UTC
