### ISSUE TITLE
CDM Asset Refactor Task Force - June 27th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2959] opened 2024-06-03 05:19 UTC
# CDM Asset Refactor Task Force Minutes
Meeting Host: Lionel Smith Gordon, Regnosys

## Date
June 27th, 2024 - 11 am ET / 4 pm BST

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve meeting minutes
   - [x] https://github.com/finos/common-domain-model/issues/2957
- [x] Securities Financing Qualification part 2. 
- [x] Phase 2 release.
- [x] AOB, Q&A & Adjourn (5mins)

**Materials**

[ARTForce 27Jun24 (1).pptx](https://github.com/user-attachments/files/16012672/ARTForce.27Jun24.1.pptx)

## Minutes

1. Minutes:
a. Minutes of 20 June approved.

2. Product Qualification: 
a. Re-capped the challenge with Product Qualification for Repo and Sec Lending.
b. Consensus agreement on the proposal that shows that Repo and Sec Lending can be differentiated with the model (pg 3):
          i.  Security Lending specifies what is being lent in an Asset Payout in Economic Terms
         ii.  Repo specifies the product using an Interest Rate Payout in Economic Terms
        iii.  Both types also have Collateral populated
        iv.  This model cannot differentiate between Repo and Buy Back and an Enum is proposed to resolve this.
c. The design of this Enum and where it is placed in the model has not been agreed; options include:
           i.  As an attribute on Economic Terms
         ii.  As an attribute on Product/ProductBase with refactoring of Product Qualification to use Product as the input.  This could also include the addition of LegalAgreement to the process.
        iii.      This will be addressed next  (ie in Phase 3 PR).
3. Second Phase PR:
a. PR has been submitted including the first two phases of changes (details in deck).
b. Participants asked to review and provide feedback.
c. Member said they are uncomfortable with some of the contents and timeline for review; how do they escalate? Suggest that they speak with ISDA to raise concerns.
d. Request that TradableProduct be removed and all of its attributes moved up to Trade.
e. Agreed approach for formal review:
          i.      Changes have been documented and circulated appropriately.
         ii.      Present PRs at CRWG.
         iii.      Seek Maintainer approval.
f. Discussion on implementation approach; refer to page 8 on samples and testing.
4. Carried forward items
a. FX
         i.      Discussion on the use of ForwardPayout for FX, is this changing?
         ii.      How should FX Forwards be modelled.
         iii.      Discussion on the concept of ‘product’ for FX trading; follow-up on ForwardPayout.
b. Need to confirm a solution for issue 2581, ie whether it is included in the Task Force scope; Tom/Lionel to address off-line.
c. Seeking clarity on the promotion of the Choice and Deep Path functionality in Rune DSL into CDM Dev so that it can be used with the refactoring; Discussion scheduled on 28 June.

5. AOB
a. Restart drop-in sessions.
b. Participants may schedule additional sessions where required.

### Zoom info
Join Zoom Meeting
https://zoom.us/j/91947398280?pwd=YS85Mmo4ejhvV2VKMlpaU1FmeDYydz09

Meeting ID: 919 4739 8280
Passcode: 867245

**Comment by JBZ-Fragmos** [comment] 2024-06-27 11:37
@Oblongs 

please could we discuss the proposed change below (whether agree to consider it in-scope or not...) 

for me would really make lot of sense (for sure per se, but notably in regards of the direction we've been moving to with having a "minimum" payout, etc.)

in one word proposed change consists in **purifying tradeLot->priceQuantity** from any attributes being (in my view) redundant, thus causing potential **overlaps/inconsistencies** with regards to similar attributes in **payoutBase** and/or in **minimum payout**

![image](https://github.com/finos/common-domain-model/assets/92978493/7df64479-52e3-42c1-a671-6c75fed1cb63)

![image](https://github.com/finos/common-domain-model/assets/92978493/65d610cb-a8e5-49df-a92c-b75bd6ba734e)

rationale : 
cf. below potential **overlaps/inconsistencies** i'm referring to in current model :
![image](https://github.com/finos/common-domain-model/assets/92978493/1bc00cf4-5e52-4ed4-bbd1-b845786deb52)

**Comment by Oblongs** [comment] 2024-06-27 15:04
Lionel Smith-Gordon for REGnosys

**Comment by d-sen-gupta** [comment] 2024-06-27 15:05
Dhruva / JPMC

**Comment by tomhealey-icma** [comment] 2024-06-27 15:06
Tom Healey/ICMA

**Comment by dschwartznyc** [comment] 2024-06-27 16:49
Dan Schwartz / FT Advisory

**Comment by dschwartznyc** [comment] 2024-06-27 17:08
Please consider moving TradeLot up a level in the model as its inclusion in TradableProduct isn't very intuitive.  From experience, at minimum a "trade" in non-OTC products is determined by the composition of a product, an amount, a settlement date and a price.  By including TradeLot (which contains PriceQuantity) in TradableProduct the current approach is in contrast to that standard approach and implies that multiple trades in the same product will lead to multiple instances of what is essentially the same product.  ![image001](https://github.com/finos/common-domain-model/assets/13089784/b8ce25e8-4d22-4a05-becf-0766029a3334)

**Comment by JBZ-Fragmos** [comment] 2024-06-28 06:36
@dschwartznyc not sure to follow your proposal or concern

kindly elaborate - thanks in advance for your answers : 
- where would you place TradeLot exactly, then ? 
- what is the "standard approach" you are referring to ?
- sorry do not understand the core issue "multiple trades in the same product will lead to multiple instances of what is essentially the same product" : please provide an example with mode details

Last feedback i would like to provide here is that at least from my experience in CDM implementation, so far hav not experiences any issues or inconsistencies etc. that would be caused by the place of TradeLot in the CDM tree... Hence why i'm asking more details to understant why you are seeing potential (or actual ?) issues about it...

Thanks
JB

**Comment by dschwartznyc** [comment] 2024-06-28 15:18
1. @JBZ-Fragmos as discussed in Thursday's session, for non-OTC derivatives products the recommendation is that tradeLot should be placed alongside TradableProduct not contained in TradableProduct.  
2. WRT products likes securities, a trade is generally determined by a product selection (ie UST 10yr note), the amount traded, the price and the settlement. 
3. It seems to me that the implication of TradableProduct continuing to contain the quantity and price of the trade is that there will be two instances of the essentially the same product for each trade whereas there should just be two trades in the same product.

Lastly - I appreciate that from the modeling of OTC derivatives this would not be an issue.  From my perspective, the issues arise when one considers the changes envisioned to better support modeling of other types of products.

**Comment by Oblongs** [comment] 2024-06-28 16:29
> 3. implication of TradableProduct continuing to contain the quantity and price of the trade is that there will be two instances of the essentially the same product for each trade whereas there should just be two trades in the same product.
> 

I don't think this is the case.  For a negotiated Product (ie OTC), there will be a large Economic Terms structure which is unlikely to ever be duplicated as each one is bespoke.
For a transferable product (eg Security), the only information that is duplicated are the product references, eg an ISIN.

The following documentation may help:  https://cdm.finos.org/docs/product-model#tradable-product

**Comment by dschwartznyc** [comment] 2024-07-01 15:48
definitely confused - looked through the documentation. Since TradableProduct contains contains tradeLot, what happends if there are two trades in the same underlying product (as described by Product)?  won't that result in two instances of what is essentially the same TradableProduct?  Wasn't this issue the motivation for moving tradeLot up a level?

**Comment by Oblongs** [comment] 2024-07-04 16:58
> TradableProduct 

Proposal presented at meeting on 3 and 4 July to resolve and accepted by @dschwartznyc

**Closed by Oblongs** 2024-07-04 16:58 UTC
Labels: meeting
